name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore RestieApi.csproj
    - name: Build
      run: dotnet build RestieApi.csproj --no-restore
    - name: Publish
      run: dotnet publish RestieApi.csproj -c Release -o RestieApi/restieapi
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: RestieApi/RestieApi/restieapi
